(()=>{'use strict';
const $=s=>document.querySelector(s);
function css(){if($('#dm-cover-eq-fix-style'))$('#dm-cover-eq-fix-style').remove();const s=document.createElement('style');s.id='dm-cover-eq-fix-style';s.textContent=`
/* COVER EDITOR — always centered */
.dm-modal.dm-cover-modal{position:fixed!important;inset:0!important;z-index:2147483647!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:14px!important;overflow:auto!important;box-sizing:border-box!important}
.dm-modal.dm-cover-modal .dm-card{width:min(620px,calc(100vw - 28px))!important;max-height:calc(100dvh - 28px)!important;margin:auto!important;overflow:auto!important;transform:none!important}
body.dm-cover-edit-open{overflow:hidden!important}
.dm-cover-editor{display:grid!important;gap:16px!important;text-align:center!important}
.dm-cover-preview{width:min(330px,72vw)!important;aspect-ratio:1!important;object-fit:cover!important;border-radius:24px!important;display:block!important;margin:0 auto!important;box-shadow:0 28px 80px #000,0 0 45px rgba(227,178,77,.12)!important}
.dm-cover-picker{position:relative!important;min-height:96px!important;border:1px dashed rgba(227,178,77,.55)!important;border-radius:20px!important;background:linear-gradient(145deg,rgba(227,178,77,.12),rgba(255,255,255,.025))!important;display:grid!important;place-items:center!important;cursor:pointer!important;transition:.2s!important;overflow:hidden!important}
.dm-cover-picker:hover{border-color:#e3b24d!important;background:linear-gradient(145deg,rgba(227,178,77,.2),rgba(255,255,255,.045))!important;transform:translateY(-1px)!important}
.dm-cover-picker strong{display:block!important;font-size:13px!important;letter-spacing:.12em!important}.dm-cover-picker span{display:block!important;margin-top:6px!important;font-size:11px!important;opacity:.52!important}.dm-cover-picker.has-file strong{color:#e3b24d!important}.dm-cover-picker input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}
/* FULL PLAYER — EQ is centered exactly around the circular cover */
.dmfp-art.dm-eq-ready{position:relative!important;isolation:isolate!important}
.dmfp-eq-ring-v3{position:absolute!important;inset:0!important;z-index:5!important;pointer-events:none!important;border-radius:50%!important}
.dmfp-eq-ring-v3:before{content:'';position:absolute;inset:7%!important;border-radius:50%!important;border:1px solid rgba(227,178,77,.28)!important;box-shadow:0 0 28px rgba(227,178,77,.13)!important}
.dmfp-eq-ring-v3 .eqv3{position:absolute!important;left:50%!important;top:50%!important;width:4px!important;height:18px!important;border-radius:99px!important;background:#e3b24d!important;box-shadow:0 0 8px rgba(227,178,77,.4)!important;opacity:.65!important;transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(.18)!important;transform-origin:center!important;animation:dmEqV3 1s ease-in-out infinite alternate!important;animation-delay:var(--d)!important}
.dmfp-art.playing .dmfp-eq-ring-v3 .eqv3{animation-duration:.38s!important;opacity:1!important}
@keyframes dmEqV3{from{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(.18)}to{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(var(--h))}}
/* MINI PLAYER — same ring size as cover, never below it */
.now-art-wrap.dm-mini-eq-ready{position:relative!important;isolation:isolate!important;display:grid!important;place-items:center!important}
.dm-mini-eq-v3{position:absolute!important;inset:-10px!important;z-index:5!important;pointer-events:none!important;border-radius:50%!important}
.dm-mini-eq-v3:before{content:'';position:absolute;inset:3px!important;border:1px solid rgba(227,178,77,.28)!important;border-radius:50%!important;box-shadow:0 0 16px rgba(227,178,77,.12)!important}
.dm-mini-eq-v3 .meq{position:absolute!important;left:50%!important;top:50%!important;width:2px!important;height:7px!important;border-radius:99px!important;background:#e3b24d!important;box-shadow:0 0 5px rgba(227,178,77,.45)!important;opacity:.58!important;transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(.2)!important;transform-origin:center!important;animation:dmMiniEqV3 .9s ease-in-out infinite alternate!important;animation-delay:var(--d)!important}
.player.playing .dm-mini-eq-v3 .meq{animation-duration:.34s!important;opacity:1!important}
@keyframes dmMiniEqV3{from{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(.2)}to{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(-1 * var(--r))) scaleY(var(--h))}}
.now-art-wrap.dm-mini-eq-ready img{border-radius:50%!important}
@media(max-width:700px){.dm-modal.dm-cover-modal{padding:10px!important}.dm-modal.dm-cover-modal .dm-card{width:calc(100vw - 20px)!important;max-height:calc(100dvh - 20px)!important;padding:18px!important}.dm-cover-preview{width:min(290px,70vw)!important}.dmfp-eq-ring-v3 .eqv3{width:3px!important;height:13px!important}.dm-mini-eq-v3{inset:-8px!important}.dm-mini-eq-v3 .meq{width:2px!important;height:6px!important}}
`;
document.head.appendChild(s)}
function coverEditorFix(root){const input=root?.querySelector?.('#dmCoverFile');if(!input||input.dataset.v3)return;input.dataset.v3='1';const modal=input.closest('.dm-modal');if(modal)modal.classList.add('dm-cover-modal');const old=input.closest('.dm-player-full')||input.parentElement;if(!old)return;old.classList.add('dm-cover-editor');const img=old.querySelector('#dmCoverPreview');if(img)img.classList.add('dm-cover-preview');let picker=old.querySelector('.dm-cover-picker');if(!picker){picker=document.createElement('label');picker.className='dm-cover-picker';picker.innerHTML='<div><strong>CHANGE COVER</strong><span>Choose JPG, PNG or WEBP · click to browse</span></div>';old.insertBefore(picker,input);picker.appendChild(input);picker.addEventListener('click',e=>{if(e.target!==input){e.preventDefault();input.click()}})}input.addEventListener('change',()=>{const f=input.files?.[0];if(!f)return;picker.classList.add('has-file');picker.querySelector('strong').textContent='✓ '+f.name;picker.querySelector('span').textContent='Image selected · press SAVE COVER'});setTimeout(()=>{modal?.scrollTo({top:0,left:0,behavior:'instant'});old.scrollIntoView({block:'center',behavior:'instant'})},0)}
function buildFullEq(){const art=$('.dmfp-art');if(!art)return;if(art.querySelector('.dmfp-eq-ring-v3'))return;art.querySelector('.dmfp-eq-ring,.dmfp-eq-ring-v2')?.remove();art.classList.add('dm-eq-ready');const ring=document.createElement('div');ring.className='dmfp-eq-ring-v3';const r=Math.max(70,Math.round(art.getBoundingClientRect().width*.46));for(let i=0;i<48;i++){const b=document.createElement('i');b.className='eqv3';b.style.setProperty('--a',`${i*7.5}deg`);b.style.setProperty('--r',`${r}px`);b.style.setProperty('--d',`${-(i%12)*.04}s`);b.style.setProperty('--h',`${.7+(i%7)*.09}`);ring.appendChild(b)}art.appendChild(ring)}
function buildMiniEq(){const w=$('.now-art-wrap');if(!w||w.querySelector('.dm-mini-eq-v3'))return;w.querySelector('.dm-mini-eq')?.remove();w.classList.add('dm-mini-eq-ready');const ring=document.createElement('div');ring.className='dm-mini-eq-v3';const r=Math.max(18,Math.round(Math.min(w.getBoundingClientRect().width,w.getBoundingClientRect().height)*.48));for(let i=0;i<28;i++){const b=document.createElement('i');b.className='meq';b.style.setProperty('--a',`${i*(360/28)}deg`);b.style.setProperty('--r',`${r}px`);b.style.setProperty('--d',`${-(i%9)*.045}s`);b.style.setProperty('--h',`${.65+(i%6)*.1}`);ring.appendChild(b)}w.appendChild(ring)}
function scan(){document.querySelectorAll('.dm-modal').forEach(m=>{if(m.querySelector('#dmCoverFile'))coverEditorFix(m)});buildFullEq();buildMiniEq()}
function init(){css();scan();const mo=new MutationObserver(scan);mo.observe(document.body,{subtree:true,childList:true});window.addEventListener('resize',()=>{document.querySelectorAll('.dmfp-eq-ring-v3,.dm-mini-eq-v3').forEach(x=>x.remove());document.querySelector('.dmfp-art')?.classList.remove('dm-eq-ready');document.querySelector('.now-art-wrap')?.classList.remove('dm-mini-eq-ready');scan()});setInterval(scan,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();