(()=>{'use strict';
const $=s=>document.querySelector(s);let audio=null,corePlay=null;
function bind(a){if(!a||audio===a)return;if(audio)audio.removeEventListener('ended',onEnded);audio=a;audio.addEventListener('ended',onEnded);audio.addEventListener('play',()=>document.querySelector('.now-art-wrap')?.classList.add('playing'));audio.addEventListener('pause',()=>document.querySelector('.now-art-wrap')?.classList.remove('playing'))}
function onEnded(){if(!audio)return;audio.currentTime=0;audio.removeAttribute('data-dmusic-ended');setTimeout(()=>document.getElementById('nextBtn')?.click(),30)}
function hook(){const native=HTMLMediaElement.prototype.play;if(native.__dmFix)return;HTMLMediaElement.prototype.play=function(){bind(this);if(this.ended||this.currentTime>=((Number.isFinite(this.duration)?this.duration:Infinity)-.05)){try{this.currentTime=0}catch{}}return native.apply(this,arguments)};HTMLMediaElement.prototype.play.__dmFix=true}
function css(){if($('#dm-final-player-fix'))return;const s=document.createElement('style');s.id='dm-final-player-fix';s.textContent=`.now-art-wrap{position:relative!important;width:72px!important;height:72px!important;min-width:72px!important;border-radius:50%!important;overflow:hidden!important}.now-art-wrap img{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:50%!important;animation:none!important}.now-art-wrap.playing img{animation:dmCDSpin 18s linear infinite!important}@keyframes dmCDSpin{to{transform:rotate(360deg)}}`;document.head.appendChild(s)}
function manualSelectionFix(){document.addEventListener('click',e=>{const row=e.target.closest('.track-row');if(!row)return;const id=row.dataset.trackId;setTimeout(()=>{if(!audio)return;const title=$('#nowTitle')?.textContent?.trim();const changed=id&&(!audio.dataset.dmusicTrackId||audio.dataset.dmusicTrackId!==id);audio.dataset.dmusicTrackId=id||title||'';if(changed){try{audio.currentTime=0}catch{}}},0)},true)}
function findAudio(){for(const a of document.querySelectorAll('audio'))bind(a);if(window.__dmusicLastAudio)bind(window.__dmusicLastAudio)}
function init(){css();hook();findAudio();manualSelectionFix();new MutationObserver(findAudio).observe(document.documentElement,{childList:true,subtree:true});setInterval(findAudio,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();