(()=>{'use strict';
const STATE_KEY='dmusic-state-v8',FALLBACK='assets/covers/fallback.svg';
let metaCache=new Map(),addedCache={};
try{addedCache=JSON.parse(localStorage.getItem('dmusic-added-v1'))||{}}catch{}
const readState=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY))||{}}catch{return{}}};
const tracks=()=>window.DMusicData?.folders?.flatMap(f=>(f.tracks||[]).map(t=>({...t,folderId:f.id,folderName:f.name,folderCover:f.cover})))||[];
const cover=t=>{try{const c=JSON.parse(localStorage.getItem('dmusic-covers-v1'))||{};return c.tracks?.[t.id]||t.cover||c.folders?.[t.folderId]||t.folderCover||FALLBACK}catch{return t.cover||t.folderCover||FALLBACK}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>{if(!Number.isFinite(s))return '—';return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`};
const ext=t=>{const n=t.fileName||t.path||t.src||'';const m=String(n).match(/\.([a-z0-9]+)(?:\?|$)/i);return m?m[1].toUpperCase():'UNKNOWN'};
const stateStats=(id,key)=>Number((readState()[key]||{})[id]||0);
function rememberAdded(){let changed=false;for(const t of tracks()){if(!addedCache[t.id]){addedCache[t.id]=Date.now();changed=true}}if(changed)localStorage.setItem('dmusic-added-v1',JSON.stringify(addedCache))}
function audioMeta(t){if(metaCache.has(t.id))return Promise.resolve(metaCache.get(t.id));return new Promise(resolve=>{const a=new Audio();let done=false;const finish=()=>{if(done)return;done=true;const duration=Number.isFinite(a.duration)?a.duration:NaN;let bitrate=NaN;const size=Number(t.file?.size||t.size||0);if(size&&duration)bitrate=(size*8/duration)/1000;const m={duration,bitrate};metaCache.set(t.id,m);a.src=t.src||'';resolve(m);setTimeout(()=>{try{a.removeAttribute('src');a.load()}catch{}},0)};a.addEventListener('loadedmetadata',finish,{once:true});a.addEventListener('error',finish,{once:true});setTimeout(finish,3500);a.src=t.src||'';try{a.load()}catch{finish()}})}
function openDetails(t){const modal=document.querySelector('.dm-details');if(!modal)return;modal.querySelector('.dm-details-cover').src=cover(t);modal.querySelector('.dm-details-title').textContent=t.title||'Untitled';modal.querySelector('.dm-details-artist').textContent=t.artist||'Unknown artist';modal.querySelector('[data-m="album"]').textContent=t.album||'Unknown album';modal.querySelector('[data-m="year"]').textContent=t.year||'—';modal.querySelector('[data-m="genre"]').textContent=t.genre||t.genres||'Unknown';modal.querySelector('[data-m="format"]').textContent=ext(t);modal.querySelector('[data-m="plays"]').textContent=stateStats(t.id,'playCounts').toLocaleString();modal.querySelector('[data-m="folder"]').textContent=t.folderName||'—';modal.classList.add('on');modal.setAttribute('aria-hidden','false');audioMeta(t).then(m=>{modal.querySelector('[data-m="duration"]').textContent=fmt(m.duration);modal.querySelector('[data-m="bitrate"]').textContent=Number.isFinite(m.bitrate)?`${Math.round(m.bitrate)} kbps (est.)`:'—'})}
function buildDetails(){if(document.querySelector('.dm-details'))return;const d=document.createElement('div');d.className='dm-details';d.setAttribute('aria-hidden','true');d.innerHTML='<div class="dm-details-card"><div class="dm-details-head"><img class="dm-details-cover" src="assets/covers/fallback.svg" alt=""><div><h2 class="dm-details-title">Track</h2><p class="dm-details-artist">Artist</p></div><button class="dm-details-close" aria-label="Close">×</button></div><div class="dm-meta-grid"><div class="dm-meta"><small>Album</small><b data-m="album">—</b></div><div class="dm-meta"><small>Year</small><b data-m="year">—</b></div><div class="dm-meta"><small>Genre</small><b data-m="genre">—</b></div><div class="dm-meta"><small>Duration</small><b data-m="duration">…</b></div><div class="dm-meta"><small>Bitrate</small><b data-m="bitrate">…</b></div><div class="dm-meta"><small>File format</small><b data-m="format">—</b></div><div class="dm-meta"><small>Folder</small><b data-m="folder">—</b></div><div class="dm-meta"><small>Play count</small><b data-m="plays">0</b></div></div><div class="dm-details-actions"><button class="dm-action" data-action="play">▶ Play</button><button class="dm-action" data-action="favorite">♡ Favorite</button></div></div>';document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('.dm-details-close')){d.classList.remove('on');d.setAttribute('aria-hidden','true');return}const act=e.target.closest('[data-action]')?.dataset.action;if(!act)return;const title=d.querySelector('.dm-details-title').textContent,t=tracks().find(x=>x.title===title);if(!t)return;if(act==='play')window.playTrack?.(t);if(act==='favorite'){const s=readState();const f=new Set(s.favorites||[]);f.has(t.id)?f.delete(t.id):f.add(t.id);s.favorites=[...f];localStorage.setItem(STATE_KEY,JSON.stringify(s));d.querySelector('[data-action="favorite"]').textContent=f.has(t.id)?'♥ Favorited':'♡ Favorite';window.render?.()}});document.addEventListener('keydown',e=>{if(e.key==='Escape')d.classList.remove('on')})}
function attachDetails(){document.querySelectorAll('.track-row-wrap').forEach(w=>{if(w.querySelector('.dm-info-btn'))return;const id=w.querySelector('.track-row')?.dataset.trackId,t=tracks().find(x=>x.id===id);if(!t)return;const b=document.createElement('button');b.className='dm-info-btn';b.title='Track details';b.textContent='i';b.onclick=e=>{e.stopPropagation();openDetails(t)};w.appendChild(b)})}
function smartData(){const a=tracks(),s=readState(),hist=s.history||{},plays=s.playCounts||{},fav=new Set(s.favorites||[]);return{added:[...a].sort((x,y)=>(addedCache[y.id]||0)-(addedCache[x.id]||0)),recent:[...a].filter(x=>hist[x.id]).sort((x,y)=>(hist[y.id]||0)-(hist[x.id]||0)),most:[...a].sort((x,y)=>(plays[y.id]||0)-(plays[x.id]||0)),favorites:a.filter(x=>fav.has(x.id)),random:[...a].sort(()=>Math.random()-.5)}}
function playList(list){if(!list.length){document.querySelector('#emptyState')?.removeAttribute('hidden');return}window.playTrack?.(list[0]);if(list.length>1){for(const t of list.slice(1,16))window.addQueue?.(t)}}
function buildSmart(){const section=document.querySelector('.tracks-section');if(!section||document.querySelector('.dm-smart'))return;const el=document.createElement('div');el.className='dm-smart';el.innerHTML='<button data-smart="added"><strong>Recently Added</strong><span>Fresh in your library</span></button><button data-smart="recent"><strong>Recently Played</strong><span>Your listening history</span></button><button data-smart="most"><strong>Most Played</strong><span>Your top tracks</span></button><button data-smart="favorites"><strong>Favorites</strong><span>Your saved tracks</span></button><button data-smart="random"><strong>Random Mix</strong><span>Surprise me</span></button>';section.querySelector('.section-title')?.after(el);el.addEventListener('click',e=>{const b=e.target.closest('[data-smart]');if(!b)return;rememberAdded();const d=smartData()[b.dataset.smart];document.querySelectorAll('.dm-smart button').forEach(x=>x.classList.remove('active'));b.classList.add('active');playList(d);const list=document.querySelector('#tracks');if(list){list.innerHTML='';d.forEach((t,i)=>{const row=document.createElement('div');row.className='track-row-wrap';row.innerHTML=`<button class="track-row" data-track-id="${esc(t.id)}"><span class="track-number">${String(i+1).padStart(2,'0')}</span><img src="${esc(cover(t))}" alt=""><span class="track-info"><b>${esc(t.title)}</b><small>${esc(t.artist||'Unknown artist')} · ${esc(t.album||'Unknown album')}</small></span><span class="track-play">▶</span></button>`;row.querySelector('.track-row').onclick=()=>window.playTrack?.(t);list.appendChild(row)});attachDetails()}})}
function ambient(){if(document.querySelector('.dm-backdrop'))return;const b=document.createElement('div');b.className='dm-backdrop';document.body.prepend(b);const update=()=>{const t=tracks().find(x=>x.id===window.currentTrack?.id)||null;if(!t)return;b.style.backgroundImage=`url("${cover(t).replace(/"/g,'')}" )`;b.classList.add('on')};setInterval(update,900);}
function visualizer(){if(document.querySelector('.dm-visualizer'))return;const v=document.createElement('div');v.className='dm-visualizer idle';for(let i=0;i<36;i++)v.appendChild(document.createElement('i'));document.body.appendChild(v);const bars=[...v.children];let ctx,analyser,data,source;const start=()=>{try{if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();analyser=ctx.createAnalyser();analyser.fftSize=128;source=ctx.createMediaElementSource(window.audio);source.connect(analyser);analyser.connect(ctx.destination);data=new Uint8Array(analyser.frequencyBinCount)}ctx.resume();v.classList.remove('idle')}catch{v.classList.add('idle')}};const loop=()=>{if(analyser&&!window.audio?.paused){analyser.getByteFrequencyData(data);bars.forEach((x,i)=>x.style.height=`${5+(data[i%data.length]/255)*34}px`)}else{v.classList.add('idle')}requestAnimationFrame(loop)};document.addEventListener('click',start,{once:false});loop()}
function loading(){if(document.querySelector('.dm-loading'))return;const l=document.createElement('div');l.className='dm-loading';l.innerHTML='<div class="dm-loading-card"><div class="dm-spinner"></div><b>Loading your music…</b></div>';document.body.appendChild(l);window.DMusicLoading={show:()=>l.classList.add('on'),hide:()=>l.classList.remove('on')}}
function transitions(){document.body.classList.add('dm-ready');document.addEventListener('click',e=>{if(e.target.closest('button,.nav-btn,.folder-card')){document.body.classList.add('dm-transition');setTimeout(()=>document.body.classList.remove('dm-transition'),280)}})}
function init(){rememberAdded();buildDetails();buildSmart();ambient();visualizer();loading();transitions();attachDetails();setTimeout(attachDetails,700);setInterval(()=>{rememberAdded();attachDetails()},2000)}window.addEventListener('load',init);window.DMusicProSuite={openDetails,smartData};})();
