(() => {
  'use strict';
  const COVER_KEY = 'dmusic-covers-v1';
  const FALLBACK = 'assets/covers/fallback.svg';
  let coverTarget = null, expanded = false, touchStartX = 0, touchStartY = 0;
  const $ = (s, root = document) => root.querySelector(s);

  function readCovers(){try{return JSON.parse(localStorage.getItem(COVER_KEY))||{folders:{},tracks:{}}}catch{return{folders:{},tracks:{}}}}
  function writeCovers(d){try{localStorage.setItem(COVER_KEY,JSON.stringify(d));return true}catch(e){console.warn('Could not save cover:',e);return false}}
  function getCover(type,id){const d=readCovers(),k=type==='folder'?'folders':'tracks';return d[k]?.[id]||''}
  function setCover(type,id,value){const d=readCovers(),k=type==='folder'?'folders':'tracks';if(value)d[k][id]=value;else delete d[k][id];return writeCovers(d)}
  function folderCover(f){return getCover('folder',f.id)||f.cover||FALLBACK}
  function trackCover(t){return getCover('track',t.id)||t.cover||t.folderCover||getCover('folder',t.folderId)||FALLBACK}
  function getTrack(id){for(const f of window.DMusicData?.folders||[]){const t=(f.tracks||[]).find(x=>x.id===id);if(t)return{...t,folderId:f.id,folderCover:f.cover}}return null}

  function addCoverButton(host,type,id,label){if(!host||host.querySelector('.cover-edit-btn'))return;const b=document.createElement('button');b.className='cover-edit-btn';b.type='button';b.title=`Change cover: ${label}`;b.setAttribute('aria-label',`Change cover for ${label}`);b.innerHTML='<span>✦</span>';b.onclick=e=>{e.preventDefault();e.stopPropagation();openCoverModal(type,id,label)};host.appendChild(b)}
  function applyCovers(){
    const folders=window.DMusicData?.folders||[];
    document.querySelectorAll('.folder-card').forEach(card=>{const name=card.querySelector('span')?.textContent?.trim(),f=folders.find(x=>x.name===name);if(f){const img=card.querySelector('img');if(img)img.src=folderCover(f);addCoverButton(card,'folder',f.id,f.name)}});
    document.querySelectorAll('.track-row-wrap').forEach(row=>{const id=row.querySelector('.track-row')?.dataset.trackId,t=id?getTrack(id):null;if(!t)return;const img=row.querySelector('.track-row img');if(img)img.src=trackCover(t);addCoverButton(row,'track',t.id,t.title)});
    const activeId=$('.track-row.active')?.dataset.trackId,t=activeId?getTrack(activeId):null,now=$('#nowCover');if(now)now.src=t?trackCover(t):FALLBACK;
  }

  function buildModal(){if($('#coverModal'))return;const m=document.createElement('div');m.id='coverModal';m.className='cover-modal';m.hidden=true;m.innerHTML=`<div class="cover-modal-backdrop"></div><div class="cover-modal-card" role="dialog" aria-modal="true" aria-labelledby="coverModalTitle"><button class="cover-modal-close" type="button" aria-label="Close">×</button><div class="cover-modal-art"><img id="coverPreview" src="${FALLBACK}" alt=""></div><div class="cover-modal-copy"><span class="section-kicker">COVER ART</span><h2 id="coverModalTitle">Change cover</h2><p id="coverModalLabel">Choose artwork for this item.</p></div><div class="cover-modal-actions"><button id="chooseCoverBtn" class="cover-action primary" type="button">UPLOAD COVER</button><button id="resetCoverBtn" class="cover-action" type="button">USE FALLBACK</button><input id="coverFileInput" type="file" accept="image/jpeg,image/png,image/webp" hidden></div></div>`;document.body.appendChild(m);$('.cover-modal-backdrop',m).onclick=closeCoverModal;$('.cover-modal-close',m).onclick=closeCoverModal;$('#chooseCoverBtn',m).onclick=()=>$('#coverFileInput',m).click();$('#resetCoverBtn',m).onclick=()=>{if(coverTarget){setCover(coverTarget.type,coverTarget.id,'');applyCovers();closeCoverModal()}};$('#coverFileInput',m).onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!coverTarget)return;try{const data=await optimizeImage(file);if(!setCover(coverTarget.type,coverTarget.id,data))throw new Error('Browser storage is full.');applyCovers();closeCoverModal()}catch(err){alert(`Could not save cover: ${err.message||'Unknown error'}`)}}}
  function optimizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Could not read image.'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Invalid image.'));img.onload=()=>{const max=1000,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.84))};img.src=r.result};r.readAsDataURL(file)})}
  function openCoverModal(type,id,label){buildModal();coverTarget={type,id,label};$('#coverPreview').src=getCover(type,id)||FALLBACK;$('#coverModalTitle').textContent=type==='folder'?'Folder cover':'Track cover';$('#coverModalLabel').textContent=label||'Choose artwork for this item.';$('#coverModal').hidden=false;requestAnimationFrame(()=>$('#coverModal').classList.add('open'))}
  function closeCoverModal(){const m=$('#coverModal');if(!m)return;m.classList.remove('open');setTimeout(()=>m.hidden=true,180);coverTarget=null}

  function addMobileNav(){if($('#mobileNav'))return;const nav=document.createElement('nav');nav.id='mobileNav';nav.className='mobile-nav';nav.innerHTML='<button data-view="library" class="mobile-nav-btn active"><span>⌂</span><small>Library</small></button><button data-view="favorites" class="mobile-nav-btn"><span>♡</span><small>Favorites</small></button><button data-view="recent" class="mobile-nav-btn"><span>◷</span><small>Recent</small></button><button data-view="playlists" class="mobile-nav-btn"><span>≡</span><small>Playlists</small></button>';document.body.appendChild(nav);nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{const old=document.querySelector(`.nav-btn[data-view="${b.dataset.view}"]`);if(old)old.click();nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));window.scrollTo({top:0,behavior:'smooth'})})}
  function addPlayerExtras(){const p=$('.player');if(!p||$('#playerExpandBtn'))return;const b=document.createElement('button');b.id='playerExpandBtn';b.className='player-expand-btn';b.type='button';b.innerHTML='⌃';b.title='Expand player';b.onclick=()=>toggleExpanded();$('.now-art-wrap',p)?.addEventListener('click',()=>toggleExpanded());p.appendChild(b)}
  function toggleExpanded(force){expanded=typeof force==='boolean'?force:!expanded;$('.player')?.classList.toggle('expanded',expanded);const b=$('#playerExpandBtn');if(b)b.textContent=expanded?'⌄':'⌃'}
  function syncPlayer(){const p=$('.player');if(!p)return;const id=$('.track-row.active')?.dataset.trackId,t=id?getTrack(id):null,now=$('#nowCover');if(now)now.src=t?trackCover(t):FALLBACK;p.classList.toggle('has-track',!!t);document.body.classList.toggle('dmusic-playing',!!t&&!$('#playBtn')?.textContent?.includes('▶'))}
  function installSwipe(){const p=$('.player');if(!p||p.dataset.swipeReady)return;p.dataset.swipeReady='1';p.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStartX=t.clientX;touchStartY=t.clientY},{passive:true});p.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.25)return;if(dx<0)$('#nextBtn')?.click();else $('#prevBtn')?.click()},{passive:true})}
  function patchRenderers(){if(window.__DMusicProRenderPatched)return;window.__DMusicProRenderPatched=true;const old=window.render;if(typeof old==='function')window.render=function(...a){const r=old.apply(this,a);requestAnimationFrame(()=>{applyCovers();syncPlayer()});return r}}
  function observeUI(){new MutationObserver(()=>{applyCovers();syncPlayer()}).observe(document.body,{childList:true,subtree:true})}
  window.DMusicPro={openCoverModal,closeCoverModal,getCover,setCover,applyCovers};
  window.addEventListener('load',()=>{buildModal();addMobileNav();addPlayerExtras();patchRenderers();installSwipe();setTimeout(()=>{applyCovers();syncPlayer()},300);setTimeout(observeUI,500)})
})();
