(()=>{'use strict';
const $=s=>document.querySelector(s),qs=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const STATE='dmusic-state-v8',RAT='dmusic-ratings-v1';
const getTracks=()=>window.DMusicData?.folders?.flatMap(f=>(f.tracks||[]).map(t=>({...t,folderId:f.id,folderName:f.name,folderCover:f.cover})))||[];
function css(){if($('#dm-hotfix-style'))$('#dm-hotfix-style').remove();const s=document.createElement('style');s.id='dm-hotfix-style';s.textContent=`
html[data-dmusic-theme=red]{--accent:#ff4d5f}html[data-dmusic-theme=blue]{--accent:#4da3ff}html[data-dmusic-theme=amoled]{--accent:#fff}html[data-dmusic-theme=amoled] body{background:#000!important}.dm-pro-dashboard{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.dm-pro-dashboard .dm-kpi{min-height:75px}.dm-perf-note{font-size:12px;opacity:.6;margin:8px 0}.track-row-wrap{content-visibility:auto;contain-intrinsic-size:72px}.tracks{contain:layout style}.dm-crop-preview{width:min(300px,70vw);aspect-ratio:1;object-fit:cover;border-radius:18px;display:block;margin:auto}.dm-visualizer-pro{pointer-events:none}.dm-visualizer-pro .dm-pro-bars{display:flex;align-items:end;gap:3px;height:52px}.dm-visualizer-pro i{display:block;width:3px;border-radius:5px 5px 0 0;min-height:4px}.dm-manager-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.dm-manager-grid button{min-height:50px}
#dmFullPlayer{position:fixed!important;inset:0!important;left:0!important;right:0!important;top:0!important;bottom:0!important;width:100vw!important;height:100dvh!important;z-index:2147483000!important;overflow:auto!important;transform:none!important}.dm-full-open{overflow:hidden!important}.dmfp-shell{min-height:100dvh!important}
.dmfp-art{position:relative!important;isolation:isolate!important;display:grid!important;place-items:center!important;width:min(470px,72vw)!important;aspect-ratio:1!important}
.dmfp-art img{position:relative!important;z-index:3!important;width:82%!important;height:82%!important;aspect-ratio:1!important;object-fit:cover!important;border-radius:50%!important;display:block!important;box-shadow:0 22px 55px #000,0 0 45px rgba(227,178,77,.13)!important;animation:dmVinylFloat 5s ease-in-out infinite!important}
.dmfp-art.playing img{animation:dmVinylSpin 18s linear infinite!important}
@keyframes dmVinylFloat{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-5px) scale(1.008)}}
@keyframes dmVinylSpin{to{transform:rotate(360deg)}}
.dmfp-art::before{content:'';position:absolute;z-index:1;width:88%;height:88%;border-radius:50%;background:repeating-radial-gradient(circle,rgba(255,255,255,.025) 0 2px,rgba(0,0,0,.08) 3px 5px);box-shadow:0 0 0 2px rgba(227,178,77,.08),0 25px 70px #000;pointer-events:none}
.dmfp-eq-ring{position:absolute!important;inset:0!important;z-index:4!important;border-radius:50%!important;pointer-events:none!important}
.dmfp-eq-ring::before{content:'';position:absolute;inset:1%;border-radius:50%;border:1px solid rgba(227,178,77,.3);box-shadow:0 0 20px rgba(227,178,77,.16),inset 0 0 18px rgba(227,178,77,.04)}
.dmfp-eq-ring .eqbar{position:absolute!important;left:50%!important;top:50%!important;width:4px!important;height:12px!important;border-radius:5px!important;background:#e3b24d!important;box-shadow:0 0 7px rgba(227,178,77,.45)!important;transform-origin:50% 0!important;transform:translate(-50%,-50%) rotate(var(--a)) translateY(-47%) scaleY(.25)!important;opacity:.72!important;animation:dmEqPulse 1s ease-in-out infinite alternate!important;animation-delay:var(--d)!important}
.dmfp-art.playing .dmfp-eq-ring .eqbar{animation-duration:.42s!important;opacity:1!important}
@keyframes dmEqPulse{from{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-47%) scaleY(.25)}to{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-47%) scaleY(1.7)}}
.now-art-wrap{position:relative!important;isolation:isolate!important}.dm-mini-eq{position:absolute!important;inset:-7px!important;border-radius:50%!important;pointer-events:none!important;z-index:4!important;border:1px solid rgba(227,178,77,.25)!important;box-shadow:0 0 15px rgba(227,178,77,.1)!important}.player.playing .dm-mini-eq{animation:dmMiniPulse .8s ease-in-out infinite alternate!important}.player.playing .now-art-wrap img{border-radius:50%!important;animation:dmMiniSpin 20s linear infinite!important}@keyframes dmMiniPulse{from{box-shadow:0 0 10px rgba(227,178,77,.08)}to{box-shadow:0 0 26px rgba(227,178,77,.3)}}@keyframes dmMiniSpin{to{transform:rotate(360deg)}}
.dm-cover-upload{position:relative!important;margin-top:12px!important;min-height:112px!important;border:1px dashed rgba(227,178,77,.42)!important;border-radius:20px!important;background:linear-gradient(145deg,rgba(227,178,77,.1),rgba(255,255,255,.025))!important;display:grid!important;place-items:center!important;text-align:center!important;overflow:hidden!important;cursor:pointer!important;transition:.2s!important}.dm-cover-upload:hover{border-color:rgba(227,178,77,.9)!important;background:rgba(227,178,77,.13)!important;transform:translateY(-1px)!important}.dm-cover-upload strong{display:block!important;font-size:13px!important;letter-spacing:.08em!important}.dm-cover-upload span{display:block!important;margin-top:6px!important;font-size:11px!important;opacity:.55!important}.dm-cover-upload input{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;opacity:0!important;cursor:pointer!important}.dm-cover-upload.has-file{border-style:solid!important;background:rgba(227,178,77,.12)!important}
@media(max-width:700px){.topbar{position:sticky;top:0;z-index:50}.main-nav{overflow-x:auto;scrollbar-width:none}.main-nav::-webkit-scrollbar{display:none}.dm-pro-tools{display:grid;grid-template-columns:repeat(2,1fr)}.dm-pro-tools button{min-height:44px}.dm-kpis{grid-template-columns:repeat(2,1fr)!important}.dm-manager-grid{grid-template-columns:1fr}.track-tools{flex-wrap:wrap}.search-box{min-width:0}.dm-toast{bottom:145px;left:12px;right:12px;text-align:center}.dmfp-art{width:min(350px,88vw)!important}.dmfp-art img{width:78%!important;height:78%!important}.dmfp-eq-ring .eqbar{width:3px!important;height:9px!important}.dmfp-eq-ring::before{inset:3%!important}}
`;document.head.appendChild(s)}
function dashboard(){if($('.dm-pro-dashboard'))return;const sec=$('.tracks-section');if(!sec)return;const d=document.createElement('div');d.className='dm-pro-dashboard';d.innerHTML='<div class="dm-kpi"><span>Tracks</span><b id="dmDashTracks">0</b></div><div class="dm-kpi"><span>Folders</span><b id="dmDashFolders">0</b></div><div class="dm-kpi"><span>Favorites</span><b id="dmDashFav">0</b></div><div class="dm-kpi"><span>Rated</span><b id="dmDashRated">0</b></div>';sec.querySelector('.section-title')?.after(d);updateDash()}
function updateDash(){const t=getTracks(),st=read(STATE,{}),r=read(RAT,{});const set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};set('dmDashTracks',t.length.toLocaleString());set('dmDashFolders',(window.DMusicData?.folders||[]).length.toLocaleString());set('dmDashFav',(st.favorites||[]).length.toLocaleString());set('dmDashRated',Object.keys(r).length.toLocaleString())}
function fixFolderData(){const fs=window.DMusicData?.folders||[];for(const f of fs){f.tracks=f.tracks||[];f.tracks.forEach(t=>{t.folderId=f.id;t.folderName=f.name})}}
function perf(){let ticking=false;document.addEventListener('input',e=>{if(!e.target.matches('#searchInput,#sortSelect,#filterSelect'))return;if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false})},{passive:true})}
function saferBackup(){const suite=window.DMusicProSuite;if(!suite)return;const b=document.querySelector('[data-pro="backup"]');if(!b||b.__safe)return;b.__safe=true;b.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();const ok=confirm('OK = Export backup\\nCancel = Restore backup');if(ok)suite.backup();else suite.restore()},true)}
function enhanceCoverUpload(root){const input=root?.querySelector?.('#dmCoverFile');if(!input||input.dataset.enhanced)return;input.dataset.enhanced='1';const old=input.parentElement;if(old?.tagName==='LABEL'&&old.classList.contains('dm-cover-upload'))return;const wrap=document.createElement('label');wrap.className='dm-cover-upload';wrap.innerHTML='<div><strong>＋ CHANGE COVER</strong><span>Choose JPG, PNG or WEBP</span></div>';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);input.addEventListener('change',()=>{if(input.files?.[0]){wrap.classList.add('has-file');wrap.querySelector('strong').textContent='✓ '+input.files[0].name;wrap.querySelector('span').textContent='Ready — press SAVE COVER'}})}
function buildEq(root){if(!root||root.querySelector('.dmfp-eq-ring'))return;const ring=document.createElement('div');ring.className='dmfp-eq-ring';for(let i=0;i<48;i++){const b=document.createElement('i');b.className='eqbar';b.style.setProperty('--a',`${i*7.5}deg`);b.style.setProperty('--d',`${-(i%12)*.045}s`);ring.appendChild(b)}root.appendChild(ring)}
function miniEq(){const w=$('.now-art-wrap');if(!w||w.querySelector('.dm-mini-eq'))return;const e=document.createElement('span');e.className='dm-mini-eq';w.appendChild(e)}
function observe(){const mo=new MutationObserver(()=>{document.querySelectorAll('.dm-modal').forEach(enhanceCoverUpload);const art=$('.dmfp-art');if(art)buildEq(art);miniEq()});mo.observe(document.body,{subtree:true,childList:true,attributes:true})}
function init(){css();fixFolderData();dashboard();perf();saferBackup();document.documentElement.dataset.dmusicTheme=read('dmusic-theme-v1','gold');miniEq();observe();setTimeout(()=>{document.querySelectorAll('.dm-modal').forEach(enhanceCoverUpload);const art=$('.dmfp-art');if(art)buildEq(art)},700);setInterval(updateDash,2500);setInterval(fixFolderData,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();