(()=>{'use strict';
const $=s=>document.querySelector(s), qs=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const STATE='dmusic-state-v8', RAT='dmusic-ratings-v1';
const getTracks=()=>window.DMusicData?.folders?.flatMap(f=>(f.tracks||[]).map(t=>({...t,folderId:f.id,folderName:f.name,folderCover:f.cover})))||[];
function css(){if($('#dm-hotfix-style'))return;const s=document.createElement('style');s.id='dm-hotfix-style';s.textContent=`html[data-dmusic-theme=red]{--accent:#ff4d5f}html[data-dmusic-theme=blue]{--accent:#4da3ff}html[data-dmusic-theme=amoled]{--accent:#fff}html[data-dmusic-theme=amoled] body{background:#000!important}.dm-pro-dashboard{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.dm-pro-dashboard .dm-kpi{min-height:75px}.dm-perf-note{font-size:12px;opacity:.6;margin:8px 0}.track-row-wrap{content-visibility:auto;contain-intrinsic-size:72px}.tracks{contain:layout style}.dm-crop-preview{width:min(300px,70vw);aspect-ratio:1;object-fit:cover;border-radius:18px;display:block;margin:auto}.dm-visualizer-pro{pointer-events:none}.dm-visualizer-pro .dm-pro-bars{display:flex;align-items:end;gap:3px;height:52px}.dm-visualizer-pro i{display:block;width:3px;border-radius:5px 5px 0 0;min-height:4px}.dm-manager-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.dm-manager-grid button{min-height:50px}
#dmFullPlayer{position:fixed!important;inset:0!important;left:0!important;right:0!important;top:0!important;bottom:0!important;width:100vw!important;height:100dvh!important;z-index:2147483000!important;overflow:auto!important;transform:none!important}.dm-full-open{overflow:hidden!important}.dmfp-shell{min-height:100dvh!important}.dmfp-art{isolation:isolate}.dmfp-art img{position:relative;z-index:2}.dmfp-eq-ring{position:absolute;inset:-25px;z-index:1;border-radius:50%;pointer-events:none;display:grid;place-items:center}.dmfp-eq-ring::before{content:'';position:absolute;inset:7px;border-radius:50%;border:1px solid rgba(227,178,77,.24);box-shadow:0 0 35px rgba(227,178,77,.12)}.dmfp-eq-ring .eqbar{position:absolute;left:50%;top:50%;width:3px;height:18px;border-radius:5px;background:#e3b24d;transform-origin:50% calc(50% + 145px);transform:translate(-50%,-50%) rotate(var(--a)) translateY(-145px) scaleY(.35);opacity:.7;animation:dmEq 1s ease-in-out infinite alternate;animation-delay:var(--d)}.dmfp-art.playing .dmfp-eq-ring .eqbar{animation-duration:.55s}.dmfp-eq-ring .eqbar:nth-child(3n){height:28px}.dmfp-eq-ring .eqbar:nth-child(4n){height:12px}.dmfp-eq-ring .eqbar:nth-child(5n){height:36px}@keyframes dmEq{from{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-145px) scaleY(.3)}to{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-145px) scaleY(1.25)}}
.now-art-wrap{position:relative;isolation:isolate}.dm-mini-eq{position:absolute;inset:-5px;border-radius:18px;pointer-events:none;z-index:3}.dm-mini-eq::before{content:'';position:absolute;inset:-3px;border-radius:20px;border:1px solid rgba(227,178,77,.18);box-shadow:0 0 18px rgba(227,178,77,.08)}.player.playing .dm-mini-eq::before{animation:dmMiniEq 1.2s ease-in-out infinite alternate}@keyframes dmMiniEq{from{box-shadow:0 0 12px rgba(227,178,77,.08)}to{box-shadow:0 0 28px rgba(227,178,77,.28)}}
.dm-cover-upload{position:relative;margin-top:12px;min-height:86px;border:1px dashed rgba(227,178,77,.38);border-radius:18px;background:linear-gradient(145deg,rgba(227,178,77,.09),rgba(255,255,255,.025));display:grid;place-items:center;text-align:center;overflow:hidden;cursor:pointer;transition:.2s}.dm-cover-upload:hover{border-color:rgba(227,178,77,.8);background:rgba(227,178,77,.12);transform:translateY(-1px)}.dm-cover-upload strong{display:block;font-size:13px}.dm-cover-upload span{display:block;margin-top:4px;font-size:11px;opacity:.5}.dm-cover-upload input{position:absolute!important;inset:0;width:100%!important;height:100%!important;opacity:0!important;cursor:pointer}.dm-cover-upload.has-file{border-style:solid}
@media(max-width:700px){.topbar{position:sticky;top:0;z-index:50}.main-nav{overflow-x:auto;scrollbar-width:none}.main-nav::-webkit-scrollbar{display:none}.dm-pro-tools{display:grid;grid-template-columns:repeat(2,1fr)}.dm-pro-tools button{min-height:44px}.dm-kpis{grid-template-columns:repeat(2,1fr)!important}.dm-manager-grid{grid-template-columns:1fr}.track-tools{flex-wrap:wrap}.search-box{min-width:0}.dm-toast{bottom:145px;left:12px;right:12px;text-align:center}.dmfp-eq-ring{inset:-16px}.dmfp-eq-ring .eqbar{transform-origin:50% calc(50% + 105px);transform:translate(-50%,-50%) rotate(var(--a)) translateY(-105px) scaleY(.35)}@keyframes dmEq{from{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-105px) scaleY(.3)}to{transform:translate(-50%,-50%) rotate(var(--a)) translateY(-105px) scaleY(1.2)}}}
`;document.head.appendChild(s)}
function dashboard(){if($('.dm-pro-dashboard'))return;const sec=$('.tracks-section');if(!sec)return;const d=document.createElement('div');d.className='dm-pro-dashboard';d.innerHTML='<div class="dm-kpi"><span>Tracks</span><b id="dmDashTracks">0</b></div><div class="dm-kpi"><span>Folders</span><b id="dmDashFolders">0</b></div><div class="dm-kpi"><span>Favorites</span><b id="dmDashFav">0</b></div><div class="dm-kpi"><span>Rated</span><b id="dmDashRated">0</b></div>';sec.querySelector('.section-title')?.after(d);updateDash()}
function updateDash(){const t=getTracks(),st=read(STATE,{}),r=read(RAT,{});const set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};set('dmDashTracks',t.length.toLocaleString());set('dmDashFolders',(window.DMusicData?.folders||[]).length.toLocaleString());set('dmDashFav',(st.favorites||[]).length.toLocaleString());set('dmDashRated',Object.keys(r).length.toLocaleString())}
function fixFolderData(){const fs=window.DMusicData?.folders||[];for(const f of fs){f.tracks=f.tracks||[];f.tracks.forEach(t=>{t.folderId=f.id;t.folderName=f.name})}}
function perf(){let ticking=false;document.addEventListener('input',e=>{if(!e.target.matches('#searchInput,#sortSelect,#filterSelect'))return;if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false})},{passive:true})}
function saferBackup(){const suite=window.DMusicProSuite;if(!suite)return;const b=document.querySelector('[data-pro="backup"]');if(!b||b.__safe)return;b.__safe=true;b.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();const ok=confirm('OK = Export backup\\nCancel = Restore backup');if(ok)suite.backup();else suite.restore()},true)}
function enhanceCoverUpload(root){const input=root?.querySelector?.('#dmCoverFile');if(!input||input.dataset.enhanced)return;input.dataset.enhanced='1';const wrap=document.createElement('label');wrap.className='dm-cover-upload';wrap.innerHTML='<div><strong>CHANGE COVER</strong><span>Click to choose an image · JPG / PNG / WEBP</span></div>';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);input.addEventListener('change',()=>{if(input.files?.[0]){wrap.classList.add('has-file');wrap.querySelector('strong').textContent=input.files[0].name;wrap.querySelector('span').textContent='Image selected — press SAVE COVER'}})}
function buildEq(root){if(!root||root.querySelector('.dmfp-eq-ring'))return;const ring=document.createElement('div');ring.className='dmfp-eq-ring';for(let i=0;i<32;i++){const b=document.createElement('i');b.className='eqbar';b.style.setProperty('--a',`${i*11.25}deg`);b.style.setProperty('--d',`${-(i%8)*.08}s`);ring.appendChild(b)}root.appendChild(ring)}
function miniEq(){const w=$('.now-art-wrap');if(!w||w.querySelector('.dm-mini-eq'))return;const e=document.createElement('span');e.className='dm-mini-eq';w.appendChild(e)}
function observe(){const mo=new MutationObserver(()=>{document.querySelectorAll('.dm-modal').forEach(enhanceCoverUpload);const art=$('.dmfp-art');if(art)buildEq(art);miniEq()});mo.observe(document.body,{subtree:true,childList:true,attributes:true})}
function init(){css();fixFolderData();dashboard();perf();saferBackup();document.documentElement.dataset.dmusicTheme=read('dmusic-theme-v1','gold');miniEq();observe();setTimeout(()=>{document.querySelectorAll('.dm-modal').forEach(enhanceCoverUpload);const art=$('.dmfp-art');if(art)buildEq(art)},700);setInterval(updateDash,2500);setInterval(fixFolderData,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();