(()=>{'use strict';
const STATE_KEY='dmusic-state-v8';
const COVER_KEY='dmusic-covers-v1';
const ADDED_KEY='dmusic-added-v2';
const HIDDEN_KEY='dmusic-hidden-v1';
const F='assets/covers/fallback.svg';
let added={},hidden={folders:{},tracks:{}};
try{added=JSON.parse(localStorage.getItem(ADDED_KEY))||{}}catch{}
try{hidden=JSON.parse(localStorage.getItem(HIDDEN_KEY))||{folders:{},tracks:{}}}catch{}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY))||{}}catch{return{}}};
const saveState=s=>localStorage.setItem(STATE_KEY,JSON.stringify(s));
const covers=()=>{try{return JSON.parse(localStorage.getItem(COVER_KEY))||{folders:{},tracks:{}}}catch{return{folders:{},tracks:{}}}};
const all=()=>window.DMusicData?.folders?.flatMap(f=>(f.tracks||[]).map(t=>({...t,folderId:f.id,folderName:f.name,folderCover:f.cover})))||[];
const visibleAll=()=>all().filter(t=>!hidden.tracks[t.id]&&!hidden.folders[t.folderId]);
const cover=t=>{const c=covers();return c.tracks?.[t.id]||t.cover||c.folders?.[t.folderId]||t.folderCover||F};
const stat=(id,k)=>Number((state()[k]||{})[id]||0);
const fmt=s=>Number.isFinite(s)&&s>=0?`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`:'—';
const ext=t=>{const n=t.fileName||t.path||'';const m=String(n).match(/\.([a-z0-9]+)$/i);return m?m[1].toUpperCase():'UNKNOWN'};
function rememberAdded(){let changed=false;for(const t of all()){if(!added[t.id]){added[t.id]=Date.now();changed=true}}if(changed)localStorage.setItem(ADDED_KEY,JSON.stringify(added))}
function find(id){return all().find(t=>t.id===id)}
function playById(id){const row=document.querySelector(`.track-row[data-track-id="${CSS.escape(String(id))}"]`);if(row){row.click();return true}return false}
function favoriteById(id){const row=document.querySelector(`.track-row[data-track-id="${CSS.escape(String(id))}"]`);const wrap=row?.closest('.track-row-wrap');const b=wrap?.querySelector('.favorite-btn');if(b){b.click();return true}return false}
function openDetails(t){const m=document.querySelector('.dm-details');if(!m)return;m.dataset.trackId=t.id;m.querySelector('.dm-details-cover').src=cover(t);m.querySelector('.dm-details-title').textContent=t.title||'Untitled';m.querySelector('.dm-details-artist').textContent=t.artist||'Unknown artist';m.querySelector('[data-m="album"]').textContent=t.album||'Unknown album';m.querySelector('[data-m="year"]').textContent=t.year||'—';m.querySelector('[data-m="genre"]').textContent=t.genre||t.genres||'Unknown';m.querySelector('[data-m="format"]').textContent=ext(t);m.querySelector('[data-m="folder"]').textContent=t.folderName||'—';m.querySelector('[data-m="plays"]').textContent=stat(t.id,'playCounts').toLocaleString();m.querySelector('[data-action="favorite"]').textContent=(state().favorites||[]).includes(t.id)?'♥ Favorited':'♡ Favorite';m.classList.add('on');m.setAttribute('aria-hidden','false');const a=new Audio();let done=false;const finish=()=>{if(done)return;done=true;const d=a.duration,size=Number(t.file?.size||t.size||0),kb=size&&Number.isFinite(d)&&d>0?(size*8/d)/1000:NaN;m.querySelector('[data-m="duration"]').textContent=fmt(d);m.querySelector('[data-m="bitrate"]').textContent=Number.isFinite(kb)?`${Math.round(kb)} kbps (est.)`:'—';try{a.src='';a.load()}catch{}};a.addEventListener('loadedmetadata',finish,{once:true});a.addEventListener('error',finish,{once:true});setTimeout(finish,2500);a.src=t.src||'';try{a.load()}catch{finish()}}
function buildDetails(){if(document.querySelector('.dm-details'))return;const d=document.createElement('div');d.className='dm-details';d.setAttribute('aria-hidden','true');d.innerHTML='<div class="dm-details-card"><div class="dm-details-head"><img class="dm-details-cover" src="assets/covers/fallback.svg" alt=""><div><h2 class="dm-details-title">Track</h2><p class="dm-details-artist">Artist</p></div><button class="dm-details-close" aria-label="Close">×</button></div><div class="dm-meta-grid"><div class="dm-meta"><small>Album</small><b data-m="album">—</b></div><div class="dm-meta"><small>Year</small><b data-m="year">—</b></div><div class="dm-meta"><small>Genre</small><b data-m="genre">—</b></div><div class="dm-meta"><small>Duration</small><b data-m="duration">…</b></div><div class="dm-meta"><small>Bitrate</small><b data-m="bitrate">…</b></div><div class="dm-meta"><small>File format</small><b data-m="format">—</b></div><div class="dm-meta"><small>Folder</small><b data-m="folder">—</b></div><div class="dm-meta"><small>Play count</small><b data-m="plays">0</b></div></div><div class="dm-details-actions"><button class="dm-action" data-action="play">▶ Play</button><button class="dm-action" data-action="favorite">♡ Favorite</button></div></div>';document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('.dm-details-close')){d.classList.remove('on');d.setAttribute('aria-hidden','true');return}const act=e.target.closest('[data-action]')?.dataset.action;if(!act)return;const t=find(d.dataset.trackId);if(!t)return;if(act==='play'){d.classList.remove('on');playById(t.id)}if(act==='favorite'){favoriteById(t.id);setTimeout(()=>{const s=state();d.querySelector('[data-action="favorite"]').textContent=(s.favorites||[]).includes(t.id)?'♥ Favorited':'♡ Favorite'},50)}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){d.classList.remove('on');d.setAttribute('aria-hidden','true')}})}
function attachDetails(){document.querySelectorAll('.track-row-wrap').forEach(w=>{if(w.querySelector('.dm-info-btn'))return;const id=w.querySelector('.track-row')?.dataset.trackId,t=find(id);if(!t)return;const b=document.createElement('button');b.className='dm-info-btn';b.type='button';b.title='Track details';b.textContent='i';b.onclick=e=>{e.stopPropagation();openDetails(t)};w.appendChild(b)})}
function smartSets(){const a=visibleAll(),s=state(),h=s.history||{},p=s.playCounts||{},fav=new Set(s.favorites||[]);return{added:[...a].sort((x,y)=>(added[y.id]||0)-(added[x.id]||0)),recent:[...a].filter(t=>h[t.id]).sort((x,y)=>(h[y.id]||0)-(h[x.id]||0)),most:[...a].sort((x,y)=>(p[y.id]||0)-(p[x.id]||0)),favorites:a.filter(t=>fav.has(t.id)),random:[...a].sort(()=>Math.random()-.5)}}
function showSet(list){const ids=new Set(list.map(t=>t.id));document.querySelectorAll('.track-row-wrap').forEach(w=>{const id=w.querySelector('.track-row')?.dataset.trackId;w.style.display=ids.has(id)?'grid':'none'});const empty=document.querySelector('#emptyState');if(empty)empty.hidden=list.length>0}
function buildSmart(){const sec=document.querySelector('.tracks-section');if(!sec||document.querySelector('.dm-smart'))return;const e=document.createElement('div');e.className='dm-smart';e.innerHTML='<button data-smart="added"><strong>Recently Added</strong><span>Fresh in your library</span></button><button data-smart="recent"><strong>Recently Played</strong><span>Listening history</span></button><button data-smart="most"><strong>Most Played</strong><span>Your top tracks</span></button><button data-smart="favorites"><strong>Favorites</strong><span>Saved tracks</span></button><button data-smart="random"><strong>Random Mix</strong><span>Shuffle your library</span></button>';sec.querySelector('.section-title')?.after(e);e.addEventListener('click',ev=>{const b=ev.target.closest('[data-smart]');if(!b)return;rememberAdded();const list=smartSets()[b.dataset.smart];e.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showSet(list);if(b.dataset.smart==='random'&&list[0])setStatus('Random Mix ready — pick a track to start.');else setStatus(`${list.length.toLocaleString()} tracks in ${b.querySelector('strong').textContent}.`)})}
function setStatus(t){const e=document.querySelector('#scanStatus');if(e)e.textContent=t}
function buildManage(){if(document.querySelector('#dmManage'))return;const b=document.createElement('button');b.id='dmManage';b.className='library-manage-btn';b.type='button';b.textContent='MANAGE LIBRARY';document.querySelector('.library-actions')?.appendChild(b);b.onclick=()=>openManager()}
function openManager(){let m=document.querySelector('.dm-manager');if(!m){m=document.createElement('div');m.className='dm-details dm-manager';m.innerHTML='<div class="dm-details-card"><div class="dm-details-head"><div><span class="section-kicker">LIBRARY TOOLS</span><h2>Manage Library</h2><p class="dm-details-artist">Safe library management</p></div><button class="dm-details-close">×</button></div><div class="dm-manager-grid"><button data-m="rename">Rename selected folder</button><button data-m="hide-folder">Remove selected folder</button><button data-m="hide-track">Remove current track</button><button data-m="rescan">Rescan folder</button><button data-m="clear">Clear library</button></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.dm-details-close')){m.classList.remove('on');return}const a=e.target.closest('[data-m]')?.dataset.m;if(a)managerAction(a)});}m.classList.add('on')}
function selectedFolder(){const cards=[...document.querySelectorAll('.folder-card.selected')];const id=cards[0]?.className?cards[0].dataset.folderId:null;return window.DMusicData?.folders?.find(f=>f.id===id)||window.DMusicData?.folders?.find(f=>f.name===document.querySelector('#tracksHeading')?.textContent)||null}
function managerAction(a){const fs=window.DMusicData?.folders||[];if(a==='rescan'){document.querySelector('#scanBtn')?.click();return}if(a==='clear'){if(!confirm('Clear the entire DMusic library? This removes saved local library data.'))return;localStorage.removeItem(STATE_KEY);localStorage.removeItem(ADDED_KEY);localStorage.removeItem(HIDDEN_KEY);indexedDB?.deleteDatabase?.('DMusicLibrary');location.reload();return}const currentId=document.querySelector('.track-row.active')?.dataset.trackId;const current=find(currentId);const heading=document.querySelector('#tracksHeading')?.textContent;let folder=fs.find(f=>f.id===window.__dmActiveFolder)||fs.find(f=>f.name===heading);if(a==='rename'){if(!folder){alert('Open a folder first.');return}const n=prompt('New folder name:',folder.name);if(n?.trim()){folder.name=n.trim();const s=JSON.parse(localStorage.getItem('dmusic-folder-names-v1')||'{}');s[folder.id]=folder.name;localStorage.setItem('dmusic-folder-names-v1',JSON.stringify(s));location.reload()}}else if(a==='hide-folder'){if(!folder){alert('Open a folder first.');return}if(confirm(`Remove “${folder.name}” from this library view?`)){hidden.folders[folder.id]=true;localStorage.setItem(HIDDEN_KEY,JSON.stringify(hidden));location.reload()}}else if(a==='hide-track'){if(!current){alert('Play/select a track first.');return}if(confirm(`Remove “${current.title}” from this library view?`)){hidden.tracks[current.id]=true;localStorage.setItem(HIDDEN_KEY,JSON.stringify(hidden));location.reload()}}}
function applyOverrides(){let names={};try{names=JSON.parse(localStorage.getItem('dmusic-folder-names-v1')||'{}')}catch{}for(const f of window.DMusicData?.folders||[]){if(names[f.id])f.name=names[f.id];if(hidden.folders[f.id]){const c=document.querySelector(`.folder-card[data-folder-id="${CSS.escape(f.id)}"]`);if(c)c.style.display='none'}}for(const t of all()){if(hidden.tracks[t.id]){const r=document.querySelector(`.track-row[data-track-id="${CSS.escape(String(t.id))}"]`)?.closest('.track-row-wrap');if(r)r.style.display='none'}}}
function addFolderIds(){document.querySelectorAll('.folder-card').forEach(c=>{const name=c.querySelector('span')?.textContent;const f=window.DMusicData?.folders?.find(x=>x.name===name);if(f)c.dataset.folderId=f.id})}
function backup(){const s=state(),c=covers();const payload={version:3,createdAt:new Date().toISOString(),library:all().map(t=>({id:t.id,title:t.title,artist:t.artist,album:t.album,year:t.year,genre:t.genre||t.genres||'',fileName:t.fileName,path:t.path,folderId:t.folderId,folderName:t.folderName})),folders:(window.DMusicData?.folders||[]).map(f=>({id:f.id,name:f.name})),state:{favorites:s.favorites||[],history:s.history||{},playCounts:s.playCounts||{},positions:s.positions||{},playlists:s.playlists||[],shuffle:s.shuffle||false,repeat:s.repeat||'off',volume:s.volume??1},covers:c,added,hidden};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`DMusic-Backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function restoreBackup(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p||!p.state)throw new Error();const s=state();Object.assign(s,p.state);saveState(s);if(p.covers)localStorage.setItem(COVER_KEY,JSON.stringify(p.covers));if(p.added)localStorage.setItem(ADDED_KEY,JSON.stringify(p.added));if(p.hidden)localStorage.setItem(HIDDEN_KEY,JSON.stringify(p.hidden));alert('Backup restored. Rescan your music folder to reconnect audio files.');location.reload()}catch{alert('Invalid DMusic backup file.')}};r.readAsText(f)};i.click()}
function buildBackup(){if(document.querySelector('#dmBackup'))return;const b=document.createElement('button');b.id='dmBackup';b.className='backup-btn';b.type='button';b.textContent='BACKUP / RESTORE';document.querySelector('.library-actions')?.appendChild(b);b.onclick=()=>{const a=prompt('1 = Export Backup\n2 = Restore Backup\n\nEnter 1 or 2');if(a==='1')backup();if(a==='2')restoreBackup()}}
function ambient(){if(document.querySelector('.dm-backdrop'))return;const b=document.createElement('div');b.className='dm-backdrop';document.body.prepend(b);const update=()=>{const img=document.querySelector('#nowCover');if(img?.src){b.style.backgroundImage=`url("${img.src.replace(/"/g,'')}" )`;b.classList.add('on')}};setInterval(update,1200)}
function visualizer(){if(document.querySelector('.dm-visualizer'))return;const v=document.createElement('div');v.className='dm-visualizer';for(let i=0;i<32;i++){const x=document.createElement('i');v.appendChild(x)}document.body.appendChild(v);let tick=0;setInterval(()=>{const playing=document.querySelector('.player.playing');v.classList.toggle('active',!!playing);if(playing){tick++;v.querySelectorAll('i').forEach((x,i)=>x.style.height=`${8+Math.abs(Math.sin(tick*.16+i*.63))*30}px`)}},90)}
function init(){rememberAdded();buildDetails();buildSmart();buildManage();buildBackup();ambient();visualizer();attachDetails();addFolderIds();applyOverrides();setTimeout(()=>{rememberAdded();attachDetails();addFolderIds();applyOverrides()},700);setInterval(()=>{rememberAdded();attachDetails();addFolderIds();applyOverrides()},1800)}
window.addEventListener('load',init);window.DMusicProSuite={openDetails,smartSets,backup,restoreBackup};})();