(()=>{'use strict';
const $=s=>document.querySelector(s), qs=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const STATE='dmusic-state-v8', META='dmusic-meta-v3', RAT='dmusic-ratings-v1', ADD='dmusic-added-v3', ST='dmusic-listen-v2';
const getTracks=()=>window.DMusicData?.folders?.flatMap(f=>(f.tracks||[]).map(t=>({...t,folderId:f.id,folderName:f.name,folderCover:f.cover})))||[];
function css(){if($('#dm-hotfix-style'))return;const s=document.createElement('style');s.id='dm-hotfix-style';s.textContent=`html[data-dmusic-theme=red]{--accent:#ff4d5f}html[data-dmusic-theme=blue]{--accent:#4da3ff}html[data-dmusic-theme=amoled]{--accent:#fff}html[data-dmusic-theme=amoled] body{background:#000!important}.dm-pro-dashboard{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.dm-pro-dashboard .dm-kpi{min-height:75px}.dm-perf-note{font-size:12px;opacity:.6;margin:8px 0}.track-row-wrap{content-visibility:auto;contain-intrinsic-size:72px}.tracks{contain:layout style}.dm-crop-preview{width:min(300px,70vw);aspect-ratio:1;object-fit:cover;border-radius:18px;display:block;margin:auto}.dm-visualizer-pro{pointer-events:none}.dm-visualizer-pro .dm-pro-bars{display:flex;align-items:end;gap:3px;height:52px}.dm-visualizer-pro i{display:block;width:3px;border-radius:5px 5px 0 0;min-height:4px}.dm-manager-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.dm-manager-grid button{min-height:50px}.dm-viewport-anchor{position:fixed!important}.player{position:fixed!important;left:18px!important;right:18px!important;bottom:14px!important;top:auto!important;transform:none!important;margin:0!important}.dm-visualizer{position:fixed!important;left:50%!important;bottom:0!important;top:auto!important;transform:translateX(-50%)!important}@media(max-width:700px){html,body{perspective:none!important;transform:none!important}.topbar{position:sticky;top:0;z-index:50}.main-nav{overflow-x:auto;scrollbar-width:none}.main-nav::-webkit-scrollbar{display:none}.player{left:8px!important;right:8px!important;bottom:82px!important;padding-bottom:max(8px,env(safe-area-inset-bottom))}.dm-pro-tools{display:grid;grid-template-columns:repeat(2,1fr)}.dm-pro-tools button{min-height:44px}.dm-kpis{grid-template-columns:repeat(2,1fr)!important}.dm-manager-grid{grid-template-columns:1fr}.track-tools{flex-wrap:wrap}.search-box{min-width:0}.dm-toast{bottom:145px;left:12px;right:12px;text-align:center}}@media(min-width:701px){html,body{perspective:none!important;transform:none!important}}`;document.head.appendChild(s)}
function dashboard(){if($('.dm-pro-dashboard'))return;const sec=$('.tracks-section');if(!sec)return;const d=document.createElement('div');d.className='dm-pro-dashboard';d.innerHTML='<div class="dm-kpi"><span>Tracks</span><b id="dmDashTracks">0</b></div><div class="dm-kpi"><span>Folders</span><b id="dmDashFolders">0</b></div><div class="dm-kpi"><span>Favorites</span><b id="dmDashFav">0</b></div><div class="dm-kpi"><span>Rated</span><b id="dmDashRated">0</b></div>';sec.querySelector('.section-title')?.after(d);updateDash()}
function updateDash(){const t=getTracks(),s=read(STATE,{}),r=read(RAT,{});const set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};set('dmDashTracks',t.length.toLocaleString());set('dmDashFolders',(window.DMusicData?.folders||[]).length.toLocaleString());set('dmDashFav',(s.favorites||[]).length.toLocaleString());set('dmDashRated',Object.keys(r).length.toLocaleString())}
function fixFolderData(){const fs=window.DMusicData?.folders||[];for(const f of fs){f.tracks=f.tracks||[];f.tracks.forEach(t=>{t.folderId=f.id;t.folderName=f.name})}}
function perf(){let ticking=false;document.addEventListener('input',e=>{if(!e.target.matches('#searchInput,#sortSelect,#filterSelect'))return;if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false})},{passive:true})}
function saferBackup(){const suite=window.DMusicProSuite;if(!suite)return;const b=document.querySelector('[data-pro="backup"]');if(!b||b.__safe)return;b.__safe=true;b.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();const ok=confirm('OK = Export backup\\nCancel = Restore backup');if(ok)suite.backup();else suite.restore()},true)}
function init(){css();fixFolderData();dashboard();perf();saferBackup();document.documentElement.dataset.dmusicTheme=read('dmusic-theme-v1','gold');setInterval(updateDash,2500);setInterval(fixFolderData,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();